## Environment for installing Mindboggle
##
## This environment is configured for circleci.com continuous integration
## (testing).
##
## Authors:
##    - Arno Klein, 2016  (arno@childmind.org)  http://binarybottle.com
##
## Copyright 2016, Child Mind Institute (childmind.org), Apache v2.0 License

#-----------------------------------------------------------------------------
# mhealthx-env environment:
#-----------------------------------------------------------------------------
name: mhealthx-env

#-----------------------------------------------------------------------------
# mindboggle dependencies:
#-----------------------------------------------------------------------------
dependencies:
    - python=3.5.1
    #-------------------------------------------------------------------------
    # nipype + (colormath, pydotplus):
    #-------------------------------------------------------------------------
    - scipy
    - networkx
    - lxml
    - simplejson
    - future
    - nose
    - pip
    - pip:
        - prov
        - traits
        - xvfbwrapper
        - https://github.com/binarybottle/mhealthx/archive/master.zip
        - colormath
        - pydotplus
    #-------------------------------------------------------------------------
    # remaining dependencies:
    #-------------------------------------------------------------------------
    #- cmake
    #- matplotlib
    - numpy
    - pandas
    #-------------------------------------------------------------------------
    # additional testing tools:
    #-------------------------------------------------------------------------
    - ipython
    - pytest
    - coverage

